### ISSUE TITLE
CV: Maxim Shchiryi

### ISSUE THREAD

**Issue by Muzikanto** [near/openweb-profiles#33]
- __GitHub Profile__: @Muzikanto
- __Available for__: `part-time` `freelance`
- __Categories__: `frontend` `backend` `development` `programming`
- __Location__: `tourkey:antalya`
- __Skills__: `rust` `near-blockchain` `nextjs` `reactjs` `typescript` `nodejs`

https://career.habr.com/muzikanto

**Comment by bancambios** [comment]
hi Maxim, we found your profile on near careers

just checking if you are currently working/coding? we have some projects on near protocol


here a link to book a call www.calendly.com/bancambios

cheers, have a good sunday
