### ISSUE TITLE
CV: Vadym Kutsenko

### ISSUE THREAD

**Issue by vadkutsen** [near/openweb-profiles#35]
- __GitHub Profile__: @vadkutsen
- __Available for__: `full-time` `part-time` `project`
- __Categories__: `development` `programming` `backend` `frontend`
- __Location__: `poland:wroclaw`
- __Skills__: `near-blockchain` `rust` `solidity` `javascript` `reactjs` `vuejs`
- [__Profile Page__](https://jobs.nearspace.info/profile/35)

#Full Stack Web3 Developer
Blockchain and crypto fan. Web3 enthusiast. Over 7 years of hands-on experience in IT (full stack web development, quality assurance, test automation). 

##Experience 
###September 2022 - **NEARCON IRL Hackathon participant**
Developed full stack web3 application with Rust smart contract on the backend and React on the frontend  
###September 2022 - **Polygon BUIDL IT: Summer 2022 hackathon winner**
Developed full stack web3 application with Solidity smart contract on the backend and React on the frontend  
###August 2022 - **TRON Grand Hackathon 2022 winner**
Developed full stack web3 application with Solidity smart contract on the backend and React on the frontend
###July 2022 - **NEAR Web4 Online Hackathon winner**
Developed full stack web4 application on NEAR in Rust  
###June 2022 - **Encode x Polygon hackathon participant**
Developed full stack web3 application with Solidity smart contract on the backend and React on the frontend  
###January 2022 - **NEAR METABUILD hackathon participant**
Developed full stack web3 application with NEAR smart contract in Rust on the backend and Vue on the frontend  
###January 2022 - **Enconde NEAR bootcamp participant**
Developed pet shelter NEAR smart contract in Rust
Developed frontend for the smart contract with near-api-js and Vue 
###November 2021 - **NEARvember challenge winner**
Developed various NEAR smart contracts (NFT, FT, voting etc.) in Rust and AssemblyScript, developed front-ends with near-api-js and React 
###October 2021 as a full stack hobbyist developer 
Created crypto currency portfolio tracker for personal use (Node+Vue) 
###January 2014 - Present -  **Senior Software QA Engineer / Test Strategist** (various companies)
#####Created QA team activity tracking and reporting full stack web application (Ruby-on-Rails) for the company's internal use.
#####Developed and maintained API test automation (Postman, Rest-Assured) and UI test automation (TS + Playwright, JS + Cypress, Java + Selenium) for various web-based projects.
#####Mentored manual testers on test automation.

##Education & Training
#####2022      NEAR x Encode Bootcamp, various blockchain development courses on buildspace.so, dacade.org, etc.
#####2021      NEARvember challenge, NEAR Academy.
#####2014–2020 various self-study web development courses. 
#####2002      Master of Science in Engineering, East Ukrainian National University, Ukraine.
#####2001      Bachelor of Science in Engineering, East Ukrainian National University, Ukraine.

##Awards
#####Polygon BUIDL IT: Summer 2022 hackathon Sponsor Prize, 2022
#####Potential Project Prize in TRON Grand Hackathon, 2022
#####NEAR Web4 Online Hackathon, 2022
#####8-th place in NEARvember challenge, 2021

##Certifications
#####NEAR Certified Developer, 2022
#####NEAR Academy Certificate of completion, 2022

##Additional Activities
Published NEAR NFT tutorial on Medium
 
##Interests
Mountain skiing, Traveling

**Comment by bancambios** [comment]
hello ser

very interesting profile, how can we chat? )
